import { useSession, signIn } from "next-auth/react";
import { useRouter } from "next/router";
import Head from "next/head";
import Hero from "@/components/hero";
import Header from "@/components/header";
import CategoryMenu from "@/components/categoryMenu";
import Combo from "@/components/combo";
import Testimonials from "@/components/testimonials";
import Footer from "@/components/footer";
import { HydrationProvider } from "react-hydration-provider";
import { useCart } from "@/context/cartContext";
import Cart from "./cart";
export default function Home() {
  const { cart } = useCart();

  console.log("index", cart.length);

  const { data: session } = useSession();

  const { push, asPath } = useRouter();

  const handleSignin = () => {
    push(`/auth/signin?callbackUrl=${asPath}`);
  };

  return (
    <>
      <Head>
        <title>Happy Shopping!🥕🥩</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HydrationProvider>
        <main className='max-w-[1200px] mx-auto'>
          <Header />
          <Hero />
          <Combo />
          <CategoryMenu />
          <Testimonials />
          <Footer />
        </main>
      </HydrationProvider>
    </>
  );
}
